### PR TITLE
765/Updating and adding colors

### PR DESCRIPTION
**Pull request by Mdemenko1**
### What (if any) features are you implementing?

Work for the issue [765](https://github.com/Gary-Community-Ventures/benefits-calculator/issues/765)

Updating color schemas

### CODE REVIEW

**Review by CalebPena — APPROVED** [review]
Looks good. Thank you for making this a priority.

**Comment by Mdemenko1** [comment]
> Looks good. Thank you for making this a priority.

@CalebPena could you merge it? I am not able to 

image

**Comment by CalebPena** [comment]
@Mdemenko1 Could you change the branch that this is merging into, to the feature branch?

**Comment by Mdemenko1** [comment]
> @Mdemenko1 Could you change the branch that this is merging into, to the feature branch?

I definitely can, however, per my conversation with @bespinosa01, he specifically mention to merge it to main

**Comment by CalebPena** [comment]
@Mdemenko1 @bespinosa01 This change affects all of the colors on the site, so we need to merge it with the other branding changes so we don't have weird mismatched colors. For example, the progress bar would look weird if we merged into main.

image

**Comment by CalebPena** [comment]
@bespinosa01 Typically for use if something is merged into main, then that means it is ready to be added to the live site. I think that a better solution would be to merge into the feature branch, and then people can pull from the feature branch to use the changes.

**Pull request merged**
